### PR TITLE
Allow supplying locale to translation functions

### PR DESCRIPTION
**Pull request by opyh**
Hey, my first pull request to this library! :)

In a recent app I need a fallback strategy to search for strings in multiple localizations (for example: `de_CH` -> `de` -> `en-US` -> untranslated original string).

To implement this without the side effects of multiple `setLocale()` calls that would change the current locale globally, I added a way to c-3po to supply a locale from the outside as argument to the translation function.

Example usage:
```javascript
import { uniq, flatten } from 'lodash';
import { tWithLocale, addLocale } from 'c-3po';

const defaultLocale = 'en_US';

addLocale('de_AT', …);
addLocale('de', …);
addLocale('en_US', …);
addLocale('en', …);

// Returns the locale as language code without country code etc. removed
// (for example "en" if given "en-GB").

function localeWithoutCountry(locale: string): string {
  return locale.substring(0, 2);
}


// Returns an expanded list of preferred locales.
export function expandedPreferredLocales() {
  // Note that some browsers don't support navigator.languages
  const localesPreferredByUser = window.navigator.languages || [];
  const locales = localesPreferredByUser.concat([window.navigator.language, defaultLocale]);

  // Try all locales without country code, too
  return uniq(flatten(locales.map(l => [l, localeWithoutCountry(l)])));
}

// This is the wrapped c-3po `t` function used throughout my app
export function t(...args) {
  for (const locale of expandedPreferredLocales()) {
    const translatedString = tWithLocale(locale, ...args);
    if (translatedString) return translatedString;
  }
  return args[0]; // return the untranslated string as last option
}
```

I did not change any existing interfaces.

Tests are green, I didn't add any new ones for the new methods though yet.

This works well for me and I think it's a cool feature. Maybe for others, too? What do you think?

### CODE REVIEW

**Comment by alxpy** [comment]
Hi! Why did you add `dist` folder?

**Comment by opyh** [comment]
Whoops! The `dist` folder commit was just a test release. It was not supposed to go into the branch. Removed it, sorry!

**Comment by AlexMost** [comment]
Hey, thanks for your PR! 

As far as I understood, you want to have an ability to set up the order of translations lookup. I think this feature will be really useful and should be present in the library and `c-3po-babel-plugin` also. The only thing I am concerned with is that `tWithLocale` and other helper functions that you have added, seems like an internal API and shouldn't be exposed to the outer world. And also, it would be great to simplify this a little bit.

As far as I see, we simply need to set up translations lookup chain somehow. Something like:

```js
import { setFallbackLocales, addLocale } from 'c-3po'

addLocale('de_AT', …);
addLocale('de', …);
addLocale('en_US', …);
addLocale('en', …);

setFallbackLocales(['de_AT', 'de', 'en_US', 'en']);
```

Pros:
1. All the details are encapsulated inside c-3po lib.
2. No need to patch an existing `t` `jt` functions.
3. That would be easier to configure inside `babel-c-3po-plugin` (simply add new configuration option - `fallbackLocales` which will be an array of locales).

@opyh what do you think?

**Comment by alxpy** [comment]
`setFallbackLocales` is good idia
@AlexMost @opyh

**Comment by AlexMost** [comment]
@opyh the desired behavior is available in the c-3po version `0.6.0`. You can update and check that. 

Here are the docs for the new method - https://c-3po.js.org/configuration-c-3po-lib.html#uselocales-string-locales

Hope that it will solve your issue. Feel free to report any problem that you will encounter or create a PR.

**Comment by opyh** [comment]
Sorry for the late reply – this is awesome. Thanks!

**Pull request closed without merging**
